/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginFrames;

import java.awt.Color;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.util.ArrayList;
import java.util.regex.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     *
     * @param usuarios
     */
    public NewUser(ArrayList<Cuenta> usuarios) {
        initComponents();
        NewUser.cuentas = usuarios;
        textf_contra_iniciar.setEchoChar((char) 0);
        textf_contraVer_crear.setEchoChar((char) 0);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel12.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bg_iniciar = new javax.swing.JPanel();
        header_iniciar = new javax.swing.JPanel();
        panel_exit_iniciar = new javax.swing.JPanel();
        label_exit_inciar = new javax.swing.JLabel();
        panel_minimize_iniciar = new javax.swing.JPanel();
        label_minimize_iniciar = new javax.swing.JLabel();
        panel_iniciarSesion = new javax.swing.JPanel();
        label_iniciarSesion = new javax.swing.JLabel();
        img_myOffice = new javax.swing.JLabel();
        panel_contra_iniciar = new javax.swing.JPanel();
        textf_contra_iniciar = new javax.swing.JPasswordField();
        icon_contra_iniciar = new javax.swing.JLabel();
        icon_visualize_iniciar = new javax.swing.JLabel();
        panel_usuario_iniciar = new javax.swing.JPanel();
        textf_usuario_iniciar = new javax.swing.JTextField();
        icon_usuario_iniciar = new javax.swing.JLabel();
        panel_ingresar_iniciar = new javax.swing.JPanel();
        label_ingresar_iniciar = new javax.swing.JLabel();
        panel_contra_iniciar1 = new javax.swing.JPanel();
        textf_contraVer_crear = new javax.swing.JPasswordField();
        icon_contra_iniciar1 = new javax.swing.JLabel();
        icon_visualize_iniciar1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        panel_bg_iniciar.setBackground(new java.awt.Color(252, 226, 219));
        panel_bg_iniciar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header_iniciar.setBackground(new java.awt.Color(122, 68, 149));
        header_iniciar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header_iniciarMouseDragged(evt);
            }
        });
        header_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_iniciarMousePressed(evt);
            }
        });

        panel_exit_iniciar.setBackground(new java.awt.Color(122, 68, 149));

        label_exit_inciar.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        label_exit_inciar.setForeground(new java.awt.Color(255, 255, 255));
        label_exit_inciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit_inciar.setText("🗙");
        label_exit_inciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exit_inciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exit_inciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exit_inciarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_exit_iniciarLayout = new javax.swing.GroupLayout(panel_exit_iniciar);
        panel_exit_iniciar.setLayout(panel_exit_iniciarLayout);
        panel_exit_iniciarLayout.setHorizontalGroup(
            panel_exit_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exit_iniciarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_exit_inciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_exit_iniciarLayout.setVerticalGroup(
            panel_exit_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_exit_inciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_minimize_iniciar.setBackground(new java.awt.Color(122, 68, 149));

        label_minimize_iniciar.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        label_minimize_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        label_minimize_iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_minimize_iniciar.setText("🗕");
        label_minimize_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_minimize_iniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_minimize_iniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_minimize_iniciarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_minimize_iniciarLayout = new javax.swing.GroupLayout(panel_minimize_iniciar);
        panel_minimize_iniciar.setLayout(panel_minimize_iniciarLayout);
        panel_minimize_iniciarLayout.setHorizontalGroup(
            panel_minimize_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_minimize_iniciarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_minimize_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_minimize_iniciarLayout.setVerticalGroup(
            panel_minimize_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_minimize_iniciar, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout header_iniciarLayout = new javax.swing.GroupLayout(header_iniciar);
        header_iniciar.setLayout(header_iniciarLayout);
        header_iniciarLayout.setHorizontalGroup(
            header_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_iniciarLayout.createSequentialGroup()
                .addGap(0, 434, Short.MAX_VALUE)
                .addComponent(panel_minimize_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_exit_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_iniciarLayout.setVerticalGroup(
            header_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_iniciarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(header_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_exit_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_minimize_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_bg_iniciar.add(header_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        panel_iniciarSesion.setBackground(new java.awt.Color(178, 112, 162));

        label_iniciarSesion.setFont(new java.awt.Font("Litera-Serial", 0, 30)); // NOI18N
        label_iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        label_iniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_iniciarSesion.setText("Crear Usuario");

        javax.swing.GroupLayout panel_iniciarSesionLayout = new javax.swing.GroupLayout(panel_iniciarSesion);
        panel_iniciarSesion.setLayout(panel_iniciarSesionLayout);
        panel_iniciarSesionLayout.setHorizontalGroup(
            panel_iniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_iniciarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_iniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_iniciarSesionLayout.setVerticalGroup(
            panel_iniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_iniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panel_bg_iniciar.add(panel_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 270, 50));

        img_myOffice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resized-removebg-preview.png"))); // NOI18N
        img_myOffice.setText("jLabel5");
        panel_bg_iniciar.add(img_myOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 140, 130));

        panel_contra_iniciar.setBackground(new java.awt.Color(204, 153, 255));

        textf_contra_iniciar.setBackground(new java.awt.Color(204, 153, 255));
        textf_contra_iniciar.setFont(new java.awt.Font("Litera-Serial", 0, 14)); // NOI18N
        textf_contra_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        textf_contra_iniciar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textf_contra_iniciar.setText("Contraseña");
        textf_contra_iniciar.setBorder(null);
        textf_contra_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textf_contra_iniciarMousePressed(evt);
            }
        });
        textf_contra_iniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textf_contra_iniciarKeyPressed(evt);
            }
        });

        icon_contra_iniciar.setBackground(new java.awt.Color(255, 0, 51));
        icon_contra_iniciar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        icon_contra_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        icon_contra_iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_contra_iniciar.setText("🔒");

        icon_visualize_iniciar.setBackground(new java.awt.Color(255, 0, 51));
        icon_visualize_iniciar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        icon_visualize_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        icon_visualize_iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_visualize_iniciar.setText("👁");
        icon_visualize_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_visualize_iniciarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_contra_iniciarLayout = new javax.swing.GroupLayout(panel_contra_iniciar);
        panel_contra_iniciar.setLayout(panel_contra_iniciarLayout);
        panel_contra_iniciarLayout.setHorizontalGroup(
            panel_contra_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contra_iniciarLayout.createSequentialGroup()
                .addComponent(icon_contra_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textf_contra_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(icon_visualize_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_contra_iniciarLayout.setVerticalGroup(
            panel_contra_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_contra_iniciarLayout.createSequentialGroup()
                .addGroup(panel_contra_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textf_contra_iniciar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_contra_iniciarLayout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(icon_contra_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
            .addComponent(icon_visualize_iniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_bg_iniciar.add(panel_contra_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 220, 30));

        panel_usuario_iniciar.setBackground(new java.awt.Color(204, 153, 255));

        textf_usuario_iniciar.setBackground(new java.awt.Color(204, 153, 255));
        textf_usuario_iniciar.setFont(new java.awt.Font("Litera-Serial", 0, 14)); // NOI18N
        textf_usuario_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        textf_usuario_iniciar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textf_usuario_iniciar.setText("Usuario");
        textf_usuario_iniciar.setBorder(null);
        textf_usuario_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textf_usuario_iniciarMousePressed(evt);
            }
        });
        textf_usuario_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textf_usuario_iniciarActionPerformed(evt);
            }
        });
        textf_usuario_iniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textf_usuario_iniciarKeyPressed(evt);
            }
        });

        icon_usuario_iniciar.setBackground(new java.awt.Color(255, 0, 51));
        icon_usuario_iniciar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        icon_usuario_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        icon_usuario_iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_usuario_iniciar.setText("👤 ");
        icon_usuario_iniciar.setMaximumSize(new java.awt.Dimension(22, 19));
        icon_usuario_iniciar.setMinimumSize(new java.awt.Dimension(22, 19));

        javax.swing.GroupLayout panel_usuario_iniciarLayout = new javax.swing.GroupLayout(panel_usuario_iniciar);
        panel_usuario_iniciar.setLayout(panel_usuario_iniciarLayout);
        panel_usuario_iniciarLayout.setHorizontalGroup(
            panel_usuario_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_usuario_iniciarLayout.createSequentialGroup()
                .addComponent(icon_usuario_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(textf_usuario_iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_usuario_iniciarLayout.setVerticalGroup(
            panel_usuario_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_usuario_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(textf_usuario_iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(icon_usuario_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_bg_iniciar.add(panel_usuario_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 220, 30));

        panel_ingresar_iniciar.setBackground(new java.awt.Color(178, 112, 162));

        label_ingresar_iniciar.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_ingresar_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        label_ingresar_iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ingresar_iniciar.setText("Registrar");
        label_ingresar_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_ingresar_iniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_ingresar_iniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_ingresar_iniciarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_ingresar_iniciarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_ingresar_iniciarLayout = new javax.swing.GroupLayout(panel_ingresar_iniciar);
        panel_ingresar_iniciar.setLayout(panel_ingresar_iniciarLayout);
        panel_ingresar_iniciarLayout.setHorizontalGroup(
            panel_ingresar_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_ingresar_iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panel_ingresar_iniciarLayout.setVerticalGroup(
            panel_ingresar_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ingresar_iniciarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_ingresar_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_bg_iniciar.add(panel_ingresar_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 90, 40));

        panel_contra_iniciar1.setBackground(new java.awt.Color(204, 153, 255));

        textf_contraVer_crear.setBackground(new java.awt.Color(204, 153, 255));
        textf_contraVer_crear.setFont(new java.awt.Font("Litera-Serial", 0, 14)); // NOI18N
        textf_contraVer_crear.setForeground(new java.awt.Color(255, 255, 255));
        textf_contraVer_crear.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textf_contraVer_crear.setText("Reingrese Contraseña");
        textf_contraVer_crear.setBorder(null);
        textf_contraVer_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textf_contraVer_crearMousePressed(evt);
            }
        });
        textf_contraVer_crear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textf_contraVer_crearKeyPressed(evt);
            }
        });

        icon_contra_iniciar1.setBackground(new java.awt.Color(255, 0, 51));
        icon_contra_iniciar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        icon_contra_iniciar1.setForeground(new java.awt.Color(255, 255, 255));
        icon_contra_iniciar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_contra_iniciar1.setText("🔒");

        icon_visualize_iniciar1.setBackground(new java.awt.Color(255, 0, 51));
        icon_visualize_iniciar1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        icon_visualize_iniciar1.setForeground(new java.awt.Color(255, 255, 255));
        icon_visualize_iniciar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_visualize_iniciar1.setText("👁");
        icon_visualize_iniciar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_visualize_iniciar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_contra_iniciar1Layout = new javax.swing.GroupLayout(panel_contra_iniciar1);
        panel_contra_iniciar1.setLayout(panel_contra_iniciar1Layout);
        panel_contra_iniciar1Layout.setHorizontalGroup(
            panel_contra_iniciar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_contra_iniciar1Layout.createSequentialGroup()
                .addComponent(icon_contra_iniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textf_contraVer_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(icon_visualize_iniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_contra_iniciar1Layout.setVerticalGroup(
            panel_contra_iniciar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_contra_iniciar1Layout.createSequentialGroup()
                .addGroup(panel_contra_iniciar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textf_contraVer_crear, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_contra_iniciar1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(icon_contra_iniciar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
            .addComponent(icon_visualize_iniciar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_bg_iniciar.add(panel_contra_iniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 220, 30));

        jLabel1.setFont(new java.awt.Font("Litera-Serial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuario Invalido. Intente de nuevo.");
        panel_bg_iniciar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 260, -1));

        jLabel2.setFont(new java.awt.Font("Litera-Serial", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contraseñas no coincidían. Intente de nuevo.");
        panel_bg_iniciar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 260, -1));

        jLabel3.setFont(new java.awt.Font("Litera-Serial", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingrese una Contraseña.");
        panel_bg_iniciar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 140, -1));

        jLabel4.setFont(new java.awt.Font("Litera-Serial", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingrese un Usuario");
        panel_bg_iniciar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 120, -1));

        jLabel5.setFont(new java.awt.Font("Litera-Serial", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reingrese la Contraseña");
        panel_bg_iniciar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 140, -1));

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        jLabel6.setFont(new java.awt.Font("Litera-Serial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Condiciones Contraseña");

        jLabel7.setFont(new java.awt.Font("Litera-Serial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("1. Incluir Minusculas");

        jLabel8.setFont(new java.awt.Font("Litera-Serial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("2. Incluir Mayusculas");

        jLabel9.setFont(new java.awt.Font("Litera-Serial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("3. Incluir caracteres especiales");

        jLabel10.setFont(new java.awt.Font("Litera-Serial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("    ej: @#$%^&+=  (sin espacios)");

        jLabel11.setFont(new java.awt.Font("Litera-Serial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("4. Debe ser 8 - 20 caracteres");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panel_bg_iniciar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 190, 150));

        jLabel12.setFont(new java.awt.Font("Litera-Serial", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Contraseña no cuenta con todas las condiciones.");
        panel_bg_iniciar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_iniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_bg_iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_exit_inciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_inciarMouseClicked
        setVisible(false);
        new DefaultLoginFrame(cuentas).setVisible(true);
    }//GEN-LAST:event_label_exit_inciarMouseClicked

    private void label_exit_inciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_inciarMouseEntered
        panel_exit_iniciar.setBackground(Color.red);
    }//GEN-LAST:event_label_exit_inciarMouseEntered

    private void label_exit_inciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_inciarMouseExited
        panel_exit_iniciar.setBackground(header_iniciar.getBackground());
    }//GEN-LAST:event_label_exit_inciarMouseExited

    private void label_minimize_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_iniciarMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_label_minimize_iniciarMouseClicked

    private void label_minimize_iniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_iniciarMouseEntered
        panel_minimize_iniciar.setBackground(new Color(122, 96, 149));
    }//GEN-LAST:event_label_minimize_iniciarMouseEntered

    private void label_minimize_iniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_iniciarMouseExited
        panel_minimize_iniciar.setBackground(header_iniciar.getBackground());
    }//GEN-LAST:event_label_minimize_iniciarMouseExited

    private void header_iniciarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_iniciarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header_iniciarMouseDragged

    private void header_iniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_iniciarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header_iniciarMousePressed

    private void textf_contra_iniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textf_contra_iniciarMousePressed
        if (textf_usuario_iniciar.getText().isEmpty()) {
            textf_usuario_iniciar.setText("Usuario");
            textf_usuario_iniciar.setForeground(Color.WHITE);
        }

        if (String.valueOf(textf_contra_iniciar.getPassword()).equals("Contraseña")) {
            textf_contra_iniciar.setText("");
            textf_contra_iniciar.setForeground(Color.WHITE);
            textf_contra_iniciar.setEchoChar('*');
            bruh = 0;
        }

        if (String.valueOf(textf_contraVer_crear.getPassword()).isEmpty()) {
            textf_contraVer_crear.setEchoChar((char) 0);
            textf_contraVer_crear.setText("Reingrese Contraseña");
            textf_contraVer_crear.setForeground(Color.WHITE);
            bruh2 = 0;
        }
    }//GEN-LAST:event_textf_contra_iniciarMousePressed

    private void textf_contra_iniciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textf_contra_iniciarKeyPressed
        if (evt.getKeyCode() == VK_ENTER) {
            textf_contraVer_crear.requestFocus();
            if (textf_usuario_iniciar.getText().isEmpty()) {
                textf_usuario_iniciar.setText("Usuario");
                textf_usuario_iniciar.setForeground(Color.WHITE);
            }

            if (String.valueOf(textf_contra_iniciar.getPassword()).isEmpty()) {
                textf_contra_iniciar.setText("Contraseña");
                textf_contra_iniciar.setForeground(Color.WHITE);
                textf_contra_iniciar.setEchoChar('*');
                bruh = 0;
            }

            if (String.valueOf(textf_contraVer_crear.getPassword()).equals("Reingrese Contraseña")) {
                textf_contraVer_crear.setEchoChar('*');
                textf_contraVer_crear.setText("");
                textf_contraVer_crear.setForeground(Color.WHITE);
                bruh2 = 0;
            }
        }
    }//GEN-LAST:event_textf_contra_iniciarKeyPressed

    private void icon_visualize_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_visualize_iniciarMouseClicked
        if (bruh == 0 && !"Contraseña".equals(textf_contra_iniciar.getText())) {
            textf_contra_iniciar.setEchoChar((char) 0);
            bruh = 1;
        } else if (bruh == 1 && !"Contraseña".equals(textf_contra_iniciar.getText())) {
            textf_contra_iniciar.setEchoChar('*');
            bruh = 0;
        } else {
            bruh = 0;
        }
    }//GEN-LAST:event_icon_visualize_iniciarMouseClicked

    private void textf_usuario_iniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textf_usuario_iniciarMousePressed
        if (textf_usuario_iniciar.getText().equals("Usuario")) {
            textf_usuario_iniciar.setText("");
            textf_usuario_iniciar.setForeground(Color.WHITE);
        }

        if (String.valueOf(textf_contra_iniciar.getPassword()).isEmpty()) {
            textf_contra_iniciar.setEchoChar((char) 0);
            textf_contra_iniciar.setText("Contraseña");
            textf_contra_iniciar.setForeground(Color.WHITE);
            bruh = 0;
        }

        if (String.valueOf(textf_contraVer_crear.getPassword()).isEmpty()) {
            textf_contraVer_crear.setEchoChar((char) 0);
            textf_contraVer_crear.setText("Reingrese Contraseña");
            textf_contraVer_crear.setForeground(Color.WHITE);
            bruh2 = 0;
        }
    }//GEN-LAST:event_textf_usuario_iniciarMousePressed

    private void textf_usuario_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textf_usuario_iniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textf_usuario_iniciarActionPerformed

    private void textf_usuario_iniciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textf_usuario_iniciarKeyPressed
        if (evt.getKeyCode() == VK_ENTER) {
            textf_contra_iniciar.requestFocus();
            if (textf_usuario_iniciar.getText().isEmpty()) {
                textf_usuario_iniciar.setText("Usuario");
                textf_usuario_iniciar.setForeground(Color.WHITE);
            }

            if (String.valueOf(textf_contra_iniciar.getPassword()).equals("Contraseña")) {
                textf_contra_iniciar.setText("");
                textf_contra_iniciar.setForeground(Color.WHITE);
                textf_contra_iniciar.setEchoChar('*');
                bruh = 0;
            }

            if (String.valueOf(textf_contraVer_crear.getPassword()).isEmpty()) {
                textf_contraVer_crear.setEchoChar((char) 0);
                textf_contraVer_crear.setText("Reingrese Contraseña");
                textf_contraVer_crear.setForeground(Color.WHITE);
                bruh2 = 0;
            }

        }
    }//GEN-LAST:event_textf_usuario_iniciarKeyPressed

    private void label_ingresar_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ingresar_iniciarMouseClicked
        if (textf_contra_iniciar.getText().equals(textf_contraVer_crear.getText()) && !textf_usuario_iniciar.getText().equals("Usuario") && !textf_contra_iniciar.getText().equals("Contraseña") && !textf_contraVer_crear.getText().equals("Reingrese Contraseña")) {
            int ver = 0;
            for (Cuenta usuario : cuentas) {
                if (usuario.getUser().equals(textf_usuario_iniciar.getText())) {
                    ver = 1;
                }
            }
            boolean contraVer = Regex(textf_contra_iniciar.getText());
            if (ver == 0) {
                if (contraVer == true) {
                    JOptionPane.showMessageDialog(this, "Ingresado Exitosamente", "Ingresado", 1);
                    jLabel12.setVisible(false);
                    jLabel1.setVisible(false);
                    jLabel2.setVisible(false);
                    jLabel3.setVisible(false);
                    jLabel4.setVisible(false);
                    jLabel5.setVisible(false);

                    setVisible(false);
                    Cuenta newCuenta = new Cuenta(textf_usuario_iniciar.getText(), textf_contra_iniciar.getText());
                    cuentas.add(newCuenta);
                    int indexCuenta = cuentas.size() - 1;
                    textf_contra_iniciar.setText("Contraseña");
                    textf_usuario_iniciar.setText("Usuario");
                    textf_contraVer_crear.setText("Reingrese Contraseña");
                    new MenuPrincipal(indexCuenta, cuentas).setVisible(true);
                } else {
                    jLabel12.setVisible(true);
                    jLabel1.setVisible(false);
                    jLabel2.setVisible(false);
                    jLabel3.setVisible(false);
                    jLabel4.setVisible(false);
                    jLabel5.setVisible(false);
                }
            } else {
                jLabel1.setVisible(true);
                jLabel12.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
            }

        } else {
            if (textf_usuario_iniciar.getText().equals("Usuario") || textf_usuario_iniciar.getText().isEmpty()) {
                jLabel4.setVisible(true);
                jLabel3.setVisible(false);
                jLabel2.setVisible(false);
                jLabel5.setVisible(false);
                jLabel1.setVisible(false);
                jLabel12.setVisible(false);
            } else if (textf_contra_iniciar.getText().equals("Contraseña") || textf_contra_iniciar.getText().isEmpty()) {
                jLabel3.setVisible(true);
                jLabel4.setVisible(false);
                jLabel2.setVisible(false);
                jLabel5.setVisible(false);
                jLabel1.setVisible(false);
                jLabel12.setVisible(false);
            } else if (textf_contraVer_crear.getText().equals("Reingrese Contraseña") || textf_contraVer_crear.getText().isEmpty()) {
                jLabel5.setVisible(true);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel1.setVisible(false);
                jLabel12.setVisible(false);

            } else if (!textf_contra_iniciar.getText().equals(textf_contraVer_crear.getText()) || (textf_contra_iniciar.getText().isEmpty() && textf_contraVer_crear.getText().isEmpty())) {
                jLabel2.setVisible(true);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel1.setVisible(false);
                jLabel12.setVisible(false);
            }

        }
    }//GEN-LAST:event_label_ingresar_iniciarMouseClicked

    private void label_ingresar_iniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ingresar_iniciarMouseEntered
        panel_ingresar_iniciar.setBackground(new Color(204, 122, 241));
    }//GEN-LAST:event_label_ingresar_iniciarMouseEntered

    private void label_ingresar_iniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ingresar_iniciarMouseExited
        panel_ingresar_iniciar.setBackground(new Color(178, 112, 162));
    }//GEN-LAST:event_label_ingresar_iniciarMouseExited

    private void label_ingresar_iniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_ingresar_iniciarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_ingresar_iniciarMousePressed

    private void textf_contraVer_crearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textf_contraVer_crearMousePressed
        if (textf_usuario_iniciar.getText().isEmpty()) {
            textf_usuario_iniciar.setText("Usuario");
            textf_usuario_iniciar.setForeground(Color.WHITE);
        }

        if (String.valueOf(textf_contra_iniciar.getPassword()).isEmpty()) {
            textf_contra_iniciar.setText("Contraseña");
            textf_contra_iniciar.setForeground(Color.WHITE);
            textf_contra_iniciar.setEchoChar('*');
            bruh = 0;
        }

        if (String.valueOf(textf_contraVer_crear.getPassword()).equals("Reingrese Contraseña")) {
            textf_contraVer_crear.setEchoChar('*');
            textf_contraVer_crear.setText("");
            textf_contraVer_crear.setForeground(Color.WHITE);
            bruh2 = 0;
        }
    }//GEN-LAST:event_textf_contraVer_crearMousePressed
    private boolean Regex(String contra) {
        String regex = "^(?=.*[0-9])"
                + "(?=.*[a-z])(?=.*[A-Z])"
                + "(?=.*[@#$%^&+=])"
                + "(?=\\S+$).{8,20}$";
        Pattern p = Pattern.compile(regex);

        if (contra == null) {
            return false;
        }

        Matcher m = p.matcher(contra);

        return m.matches();
    }
    private void textf_contraVer_crearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textf_contraVer_crearKeyPressed
        if (evt.getKeyCode() == VK_ENTER) {
            label_ingresar_iniciarMouseClicked(new java.awt.event.MouseEvent(this, 1, 1, 1, 1, 1, 1, rootPaneCheckingEnabled));
        }
    }//GEN-LAST:event_textf_contraVer_crearKeyPressed

    private void icon_visualize_iniciar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_visualize_iniciar1MouseClicked
        if (bruh2 == 0 && !"Reingrese Contraseña".equals(textf_contraVer_crear.getText())) {
            textf_contraVer_crear.setEchoChar((char) 0);
            bruh2 = 1;
        } else if (bruh2 == 1 && !"Reingrese Contraseña".equals(textf_contraVer_crear.getText())) {
            textf_contraVer_crear.setEchoChar('*');
            bruh2 = 0;
        } else {
            bruh2 = 0;
        }
    }//GEN-LAST:event_icon_visualize_iniciar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser(cuentas).setVisible(true);
            }
        });
    }
    private int bruh = 0;
    private int bruh2 = 0;
    private int xMouse;
    private int yMouse;
    private static ArrayList<Cuenta> cuentas;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header_iniciar;
    private javax.swing.JLabel icon_contra_iniciar;
    private javax.swing.JLabel icon_contra_iniciar1;
    private javax.swing.JLabel icon_usuario_iniciar;
    private javax.swing.JLabel icon_visualize_iniciar;
    private javax.swing.JLabel icon_visualize_iniciar1;
    private javax.swing.JLabel img_myOffice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_exit_inciar;
    private javax.swing.JLabel label_ingresar_iniciar;
    private javax.swing.JLabel label_iniciarSesion;
    private javax.swing.JLabel label_minimize_iniciar;
    private javax.swing.JPanel panel_bg_iniciar;
    private javax.swing.JPanel panel_contra_iniciar;
    private javax.swing.JPanel panel_contra_iniciar1;
    private javax.swing.JPanel panel_exit_iniciar;
    private javax.swing.JPanel panel_ingresar_iniciar;
    private javax.swing.JPanel panel_iniciarSesion;
    private javax.swing.JPanel panel_minimize_iniciar;
    private javax.swing.JPanel panel_usuario_iniciar;
    private javax.swing.JPasswordField textf_contraVer_crear;
    private javax.swing.JPasswordField textf_contra_iniciar;
    private javax.swing.JTextField textf_usuario_iniciar;
    // End of variables declaration//GEN-END:variables
}
