package Clases;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ToDo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ToDo
     */
    public ToDo() {
        initComponents();
        vaciarTabla();
    }

    public void vaciarTabla() {
        DefaultTableModel Modelo = (DefaultTableModel) jTable1.getModel();
        String titulos[] = {"ID", "NOMBRE_Tarea", "FechaTarea", "Realizado", "Importante","ID_tarea"};
        Modelo = new DefaultTableModel(null, titulos);
        jTable1.setModel(Modelo);
    }

    public void verDatos(){
//        try {
//            Connection con1 = null;
//            DefaultTableModel miModelo = (DefaultTableModel) jTable1.getModel();
//            Conexion conect1 = new Conexion();
//            con1 = conect1.getConnection();
//            Object dts[] = new String[6];
//            String sql = "select * from ToDo";
//            Statement st = con1.createStatement();
//            ResultSet rs = st.executeQuery(sql);
//            while(rs.next()){
//                dts[0] = rs.getString("id_cuenta");
//                dts[1] = rs.getString("nombre_Tarea");
//                dts[2] = rs.getString("fechaRealizar_tarea");
//                dts[3] = rs.getBoolean("realizado_tarea");
//                dts[4] = rs.getBoolean("importante_tarea");
//                dts[5] = rs.getString("id_tarea");
//                miModelo.addRow(dts);
//            }
//            jTable1.setModel(miModelo);
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, "NO SE PUEDEN VISUALIZAR LOS DATOS DE LA TABLA", "Error", JOptionPane.ERROR_MESSAGE);
//        }
    }
    
    public void AgregarDatos(){
//        Connection con1 = null;
//            DefaultTableModel miModelo = (DefaultTableModel) jTable1.getModel();
//            Conexion conect1 = new Conexion();
//            con1 = conect1.getConnection();
//            //String nombreTarea, fechaRealizar, 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_cuenta", "nombre_Tarea", "nota_tarea", "fechaRealizar_tarea", "id_listasTareas", "realizado_tarea", "importante_tarea", "id_lista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
