package ToDo;

import Conexiones.Dba;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import loginFrames.Administrador;
import loginFrames.Cuenta;
import loginFrames.DefaultLoginFrame;
import loginFrames.MenuPrincipal;

/**
 *
 * @author Usuario
 */
public class myToDo extends javax.swing.JFrame {

    /**
     * Creates new form myToDo
     *
     * @param indexCuenta
     */
    public myToDo(int indexCuenta) {
        initComponents();
        traerCuenta();
        traerTareas();
        myToDo.indexCuenta = indexCuenta;
        dateChooser.getJCalendar().setMinSelectableDate(new Date());
        table_listaTareas.getTableHeader().setFont(new java.awt.Font("Litera-Serial", 0, 14));
        table_listaTareas.getTableHeader().setBackground(new Color(255, 152, 204));
        table_listaTareas.getTableHeader().setForeground(Color.WHITE);
        table_myDay.getTableHeader().setFont(new java.awt.Font("Litera-Serial", Font.BOLD, 15));
        table_myDay.getTableHeader().setBackground(new Color(255, 152, 204));
        table_myDay.getTableHeader().setForeground(Color.WHITE);
        table_completados.getTableHeader().setFont(new java.awt.Font("Litera-Serial", Font.BOLD, 15));
        table_completados.getTableHeader().setBackground(new Color(255, 152, 204));
        table_completados.getTableHeader().setForeground(Color.WHITE);
        table_importante.getTableHeader().setFont(new java.awt.Font("Litera-Serial", Font.BOLD, 15));
        table_importante.getTableHeader().setBackground(new Color(255, 152, 204));
        table_importante.getTableHeader().setForeground(Color.WHITE);
        jScrollPane2.setPreferredSize(new Dimension(Integer.MAX_VALUE, (table_myDay.getRowCount() + 1) * table_myDay.getRowHeight()));
        table_myDay.getColumnModel().getColumn(0).setPreferredWidth(23);
        table_myDay.getColumnModel().getColumn(1).setPreferredWidth(140);
        table_myDay.getColumnModel().getColumn(2).setPreferredWidth(23);
        table_myDay.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        table_importante.getColumnModel().getColumn(0).setPreferredWidth(160);
        table_importante.getColumnModel().getColumn(1).setPreferredWidth(30);
        table_importante.getColumnModel().getColumn(2).setPreferredWidth(23);
        table_importante.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        table_completados.getColumnModel().getColumn(0).setPreferredWidth(160);
        table_completados.getColumnModel().getColumn(1).setPreferredWidth(40);
        table_completados.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        table_listaTareas.setTableHeader(null);
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        panel_completados.setVisible(false);
        panel_importante.setVisible(false);
        jPanel10.setVisible(true);
        label_myDayMouseClicked(new java.awt.event.MouseEvent(this, 1, 1, 1, 1, 1, 1, false));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        bg_myToDo = new javax.swing.JPanel();
        header_menu = new javax.swing.JPanel();
        panel_minimize_myToDo = new javax.swing.JPanel();
        label_minimize_myToDo = new javax.swing.JLabel();
        panel_exit_myToDo = new javax.swing.JPanel();
        label_exit_myToDo = new javax.swing.JLabel();
        panel_eventos = new javax.swing.JPanel();
        panel_myDay = new javax.swing.JPanel();
        label_myDay = new javax.swing.JLabel();
        panel_important = new javax.swing.JPanel();
        label_importante = new javax.swing.JLabel();
        panel_tareasAsignadas = new javax.swing.JPanel();
        label_tareasAsignadas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panel_tareasRealizadas = new javax.swing.JPanel();
        label_tareasRealizadas = new javax.swing.JLabel();
        panel_listasTareas = new javax.swing.JPanel();
        label_listasTareas = new javax.swing.JLabel();
        myDay_Title = new javax.swing.JLabel();
        panel_crearLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_listaTareas = new javax.swing.JTable();
        panel_asignarTarea = new javax.swing.JPanel();
        label_listasTareas1 = new javax.swing.JLabel();
        panel_tareasDay = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_myDay = new javax.swing.JTable();
        panel_importante = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_importante = new javax.swing.JTable();
        panel_completados = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_completados = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg_myToDo.setBackground(new java.awt.Color(252, 255, 219));
        bg_myToDo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header_menu.setBackground(new java.awt.Color(122, 68, 149));
        header_menu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header_menuMouseDragged(evt);
            }
        });
        header_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_menuMousePressed(evt);
            }
        });

        panel_minimize_myToDo.setBackground(new java.awt.Color(122, 68, 149));

        label_minimize_myToDo.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        label_minimize_myToDo.setForeground(new java.awt.Color(255, 255, 255));
        label_minimize_myToDo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_minimize_myToDo.setText("🗕");
        label_minimize_myToDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_minimize_myToDoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_minimize_myToDoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_minimize_myToDoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_minimize_myToDoLayout = new javax.swing.GroupLayout(panel_minimize_myToDo);
        panel_minimize_myToDo.setLayout(panel_minimize_myToDoLayout);
        panel_minimize_myToDoLayout.setHorizontalGroup(
            panel_minimize_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_minimize_myToDoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_minimize_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_minimize_myToDoLayout.setVerticalGroup(
            panel_minimize_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_minimize_myToDoLayout.createSequentialGroup()
                .addComponent(label_minimize_myToDo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_exit_myToDo.setBackground(new java.awt.Color(122, 68, 149));

        label_exit_myToDo.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        label_exit_myToDo.setForeground(new java.awt.Color(255, 255, 255));
        label_exit_myToDo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit_myToDo.setText("🗙");
        label_exit_myToDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exit_myToDoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exit_myToDoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exit_myToDoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_exit_myToDoLayout = new javax.swing.GroupLayout(panel_exit_myToDo);
        panel_exit_myToDo.setLayout(panel_exit_myToDoLayout);
        panel_exit_myToDoLayout.setHorizontalGroup(
            panel_exit_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exit_myToDoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_exit_myToDoLayout.setVerticalGroup(
            panel_exit_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exit_myToDoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout header_menuLayout = new javax.swing.GroupLayout(header_menu);
        header_menu.setLayout(header_menuLayout);
        header_menuLayout.setHorizontalGroup(
            header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_menuLayout.createSequentialGroup()
                .addContainerGap(934, Short.MAX_VALUE)
                .addComponent(panel_minimize_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_menuLayout.setVerticalGroup(
            header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_menuLayout.createSequentialGroup()
                .addGroup(header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_minimize_myToDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(header_menuLayout.createSequentialGroup()
                        .addComponent(panel_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bg_myToDo.add(header_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        panel_eventos.setBackground(new java.awt.Color(172, 112, 168));

        panel_myDay.setBackground(new java.awt.Color(153, 0, 153));

        label_myDay.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_myDay.setForeground(new java.awt.Color(255, 255, 255));
        label_myDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_myDay.setText("My Day");
        label_myDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_myDayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_myDayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_myDayMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_myDayLayout = new javax.swing.GroupLayout(panel_myDay);
        panel_myDay.setLayout(panel_myDayLayout);
        panel_myDayLayout.setHorizontalGroup(
            panel_myDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_myDayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_myDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_myDayLayout.setVerticalGroup(
            panel_myDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_myDay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_important.setBackground(new java.awt.Color(153, 0, 153));

        label_importante.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_importante.setForeground(new java.awt.Color(255, 255, 255));
        label_importante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_importante.setText("Importante");
        label_importante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_importanteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_importanteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_importanteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_importantLayout = new javax.swing.GroupLayout(panel_important);
        panel_important.setLayout(panel_importantLayout);
        panel_importantLayout.setHorizontalGroup(
            panel_importantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_importantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_importante, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_importantLayout.setVerticalGroup(
            panel_importantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_importante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_tareasAsignadas.setBackground(new java.awt.Color(153, 0, 153));

        label_tareasAsignadas.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_tareasAsignadas.setForeground(new java.awt.Color(255, 255, 255));
        label_tareasAsignadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tareasAsignadas.setText("Tareas Asignadas");
        label_tareasAsignadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_tareasAsignadasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_tareasAsignadasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_tareasAsignadasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_tareasAsignadasLayout = new javax.swing.GroupLayout(panel_tareasAsignadas);
        panel_tareasAsignadas.setLayout(panel_tareasAsignadasLayout);
        panel_tareasAsignadasLayout.setHorizontalGroup(
            panel_tareasAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tareasAsignadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_tareasAsignadas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tareasAsignadasLayout.setVerticalGroup(
            panel_tareasAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_tareasAsignadas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(102, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 0, 102));

        panel_tareasRealizadas.setBackground(new java.awt.Color(153, 0, 153));

        label_tareasRealizadas.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_tareasRealizadas.setForeground(new java.awt.Color(255, 255, 255));
        label_tareasRealizadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tareasRealizadas.setText("Tareas Realizadas");
        label_tareasRealizadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_tareasRealizadasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_tareasRealizadasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_tareasRealizadasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_tareasRealizadasLayout = new javax.swing.GroupLayout(panel_tareasRealizadas);
        panel_tareasRealizadas.setLayout(panel_tareasRealizadasLayout);
        panel_tareasRealizadasLayout.setHorizontalGroup(
            panel_tareasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tareasRealizadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_tareasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tareasRealizadasLayout.setVerticalGroup(
            panel_tareasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_tareasRealizadas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_listasTareas.setBackground(new java.awt.Color(153, 0, 153));

        label_listasTareas.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_listasTareas.setForeground(new java.awt.Color(255, 255, 255));
        label_listasTareas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_listasTareas.setText("+ Lista de Tareas");
        label_listasTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_listasTareasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_listasTareasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_listasTareasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_listasTareasLayout = new javax.swing.GroupLayout(panel_listasTareas);
        panel_listasTareas.setLayout(panel_listasTareasLayout);
        panel_listasTareasLayout.setHorizontalGroup(
            panel_listasTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_listasTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_listasTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_listasTareasLayout.setVerticalGroup(
            panel_listasTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_listasTareas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        myDay_Title.setFont(new java.awt.Font("Litera-Serial", 0, 36)); // NOI18N
        myDay_Title.setForeground(new java.awt.Color(255, 255, 255));
        myDay_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myDay_Title.setText("myDay");

        panel_crearLista.setBackground(new java.awt.Color(153, 0, 153));

        table_listaTareas.setBackground(new java.awt.Color(204, 51, 255));
        table_listaTareas.setFont(new java.awt.Font("Litera-Serial", 0, 12)); // NOI18N
        table_listaTareas.setForeground(new java.awt.Color(255, 255, 255));
        table_listaTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"HOLA"},
                {"ADIOS"},
                {null}
            },
            new String [] {
                "Lista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_listaTareas.setFocusable(false);
        table_listaTareas.setGridColor(new java.awt.Color(204, 153, 255));
        table_listaTareas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_listaTareas.setRowHeight(25);
        table_listaTareas.setRowSelectionAllowed(false);
        table_listaTareas.setShowHorizontalLines(false);
        table_listaTareas.setShowVerticalLines(false);
        jScrollPane1.setViewportView(table_listaTareas);

        javax.swing.GroupLayout panel_crearListaLayout = new javax.swing.GroupLayout(panel_crearLista);
        panel_crearLista.setLayout(panel_crearListaLayout);
        panel_crearListaLayout.setHorizontalGroup(
            panel_crearListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crearListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_crearListaLayout.setVerticalGroup(
            panel_crearListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crearListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        panel_asignarTarea.setBackground(new java.awt.Color(153, 0, 153));

        label_listasTareas1.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_listasTareas1.setForeground(new java.awt.Color(255, 255, 255));
        label_listasTareas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_listasTareas1.setText("+ Asignar Tarea");
        label_listasTareas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_listasTareas1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_listasTareas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_listasTareas1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_asignarTareaLayout = new javax.swing.GroupLayout(panel_asignarTarea);
        panel_asignarTarea.setLayout(panel_asignarTareaLayout);
        panel_asignarTareaLayout.setHorizontalGroup(
            panel_asignarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_asignarTareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_listasTareas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_asignarTareaLayout.setVerticalGroup(
            panel_asignarTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_listasTareas1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_eventosLayout = new javax.swing.GroupLayout(panel_eventos);
        panel_eventos.setLayout(panel_eventosLayout);
        panel_eventosLayout.setHorizontalGroup(
            panel_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_myDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_important, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_tareasAsignadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_tareasRealizadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_listasTareas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_eventosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(myDay_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_crearLista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_asignarTarea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_eventosLayout.setVerticalGroup(
            panel_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_eventosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(myDay_Title)
                .addGap(18, 18, 18)
                .addComponent(panel_myDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_important, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tareasAsignadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tareasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_asignarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_listasTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_crearLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg_myToDo.add(panel_eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 520));

        panel_tareasDay.setBackground(new java.awt.Color(172, 112, 168));

        table_myDay.setBackground(new java.awt.Color(255, 153, 255));
        table_myDay.setFont(new java.awt.Font("Litera-Serial", 0, 14)); // NOI18N
        table_myDay.setForeground(new java.awt.Color(255, 255, 255));
        table_myDay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Importante", "Tarea", "Fecha Limite", "Completado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_myDay.setGridColor(new java.awt.Color(102, 0, 102));
        table_myDay.setOpaque(false);
        table_myDay.setRowHeight(25);
        table_myDay.setSelectionBackground(new java.awt.Color(204, 51, 255));
        table_myDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_myDayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_myDay);

        javax.swing.GroupLayout panel_tareasDayLayout = new javax.swing.GroupLayout(panel_tareasDay);
        panel_tareasDay.setLayout(panel_tareasDayLayout);
        panel_tareasDayLayout.setHorizontalGroup(
            panel_tareasDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tareasDayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_tareasDayLayout.setVerticalGroup(
            panel_tareasDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tareasDayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg_myToDo.add(panel_tareasDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 570, 440));

        panel_importante.setBackground(new java.awt.Color(172, 112, 168));

        table_importante.setBackground(new java.awt.Color(255, 153, 255));
        table_importante.setFont(new java.awt.Font("Litera-Serial", 0, 14)); // NOI18N
        table_importante.setForeground(new java.awt.Color(255, 255, 255));
        table_importante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Fecha Limite", "Completado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_importante.setGridColor(new java.awt.Color(102, 0, 102));
        table_importante.setOpaque(false);
        table_importante.setRowHeight(25);
        table_importante.setSelectionBackground(new java.awt.Color(204, 51, 255));
        table_importante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_importanteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_importante);

        javax.swing.GroupLayout panel_importanteLayout = new javax.swing.GroupLayout(panel_importante);
        panel_importante.setLayout(panel_importanteLayout);
        panel_importanteLayout.setHorizontalGroup(
            panel_importanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_importanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_importanteLayout.setVerticalGroup(
            panel_importanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_importanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg_myToDo.add(panel_importante, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 570, 440));

        panel_completados.setBackground(new java.awt.Color(204, 102, 255));

        table_completados.setBackground(new java.awt.Color(255, 153, 255));
        table_completados.setFont(new java.awt.Font("Litera-Serial", 0, 14)); // NOI18N
        table_completados.setForeground(new java.awt.Color(255, 255, 255));
        table_completados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Fecha Limite"
            }
        ));
        table_completados.setGridColor(new java.awt.Color(102, 0, 102));
        table_completados.setRowHeight(25);
        table_completados.setSelectionBackground(new java.awt.Color(204, 51, 255));
        jScrollPane4.setViewportView(table_completados);

        javax.swing.GroupLayout panel_completadosLayout = new javax.swing.GroupLayout(panel_completados);
        panel_completados.setLayout(panel_completadosLayout);
        panel_completadosLayout.setHorizontalGroup(
            panel_completadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_completadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_completadosLayout.setVerticalGroup(
            panel_completadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_completadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg_myToDo.add(panel_completados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 570, 440));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        bg_myToDo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 570, 440));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        bg_myToDo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 570, 440));

        jPanel2.setBackground(new java.awt.Color(172, 112, 168));
        jPanel2.setForeground(new java.awt.Color(204, 102, 255));

        jTextArea1.setBackground(new java.awt.Color(153, 153, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Litera-Serial", 0, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(204, 0, 204));

        jLabel3.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg_myToDo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 190, 230));
        bg_myToDo.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 190, -1));

        jPanel7.setBackground(new java.awt.Color(172, 112, 168));

        jTextField1.setBackground(new java.awt.Color(172, 112, 168));
        jTextField1.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Agregar Tarea");
        jTextField1.setBorder(null);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("+");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        bg_myToDo.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 570, 30));

        jPanel8.setBackground(new java.awt.Color(172, 112, 168));

        jLabel2.setFont(new java.awt.Font("Litera-Serial", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha de Vencimiento");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg_myToDo.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 190, 30));

        jPanel10.setBackground(new java.awt.Color(172, 112, 168));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Notas");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(69, 69, 69))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg_myToDo.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_myToDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_myToDo, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_minimize_myToDoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_myToDoMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_label_minimize_myToDoMouseClicked

    private void label_minimize_myToDoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_myToDoMouseEntered
        panel_minimize_myToDo.setBackground(new Color(122, 96, 149));
    }//GEN-LAST:event_label_minimize_myToDoMouseEntered

    private void label_minimize_myToDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_myToDoMouseExited
        panel_minimize_myToDo.setBackground(header_menu.getBackground());
    }//GEN-LAST:event_label_minimize_myToDoMouseExited

    private void label_exit_myToDoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myToDoMouseClicked
        int yesno = JOptionPane.showConfirmDialog(this, "Salir y guardar cambios?", "Salir", 0);
        if (yesno == 0) {
            if ("Kevin".equals(cuentas.get(indexCuenta).getUser())) {
                setVisible(false);
                new Administrador(indexCuenta).setVisible(true);
            } else {
                setVisible(false);
                new MenuPrincipal(indexCuenta).setVisible(true);
            }
        }
    }//GEN-LAST:event_label_exit_myToDoMouseClicked

    private void label_exit_myToDoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myToDoMouseEntered
        panel_exit_myToDo.setBackground(Color.red);
    }//GEN-LAST:event_label_exit_myToDoMouseEntered

    private void label_exit_myToDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myToDoMouseExited
        panel_exit_myToDo.setBackground(header_menu.getBackground());
    }//GEN-LAST:event_label_exit_myToDoMouseExited

    private void header_menuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_menuMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header_menuMouseDragged

    private void header_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_menuMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header_menuMousePressed

    private void label_myDayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_myDayMouseEntered
        panel_myDay.setBackground(new Color(195, 0, 195));
    }//GEN-LAST:event_label_myDayMouseEntered

    private void label_myDayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_myDayMouseExited
        panel_myDay.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_myDayMouseExited

    private void label_importanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_importanteMouseEntered
        panel_important.setBackground(new Color(195, 0, 195));
    }//GEN-LAST:event_label_importanteMouseEntered

    private void label_importanteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_importanteMouseExited
        panel_important.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_importanteMouseExited

    private void label_tareasAsignadasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tareasAsignadasMouseEntered
        panel_tareasAsignadas.setBackground(new Color(195, 0, 195));
    }//GEN-LAST:event_label_tareasAsignadasMouseEntered

    private void label_tareasAsignadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tareasAsignadasMouseExited
        panel_tareasAsignadas.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_tareasAsignadasMouseExited

    private void label_tareasRealizadasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tareasRealizadasMouseEntered
        panel_tareasRealizadas.setBackground(new Color(195, 0, 195));
    }//GEN-LAST:event_label_tareasRealizadasMouseEntered

    private void label_tareasRealizadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tareasRealizadasMouseExited
        panel_tareasRealizadas.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_tareasRealizadasMouseExited

    private void label_listasTareasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_listasTareasMouseEntered
        panel_listasTareas.setBackground(new Color(195, 0, 195));
    }//GEN-LAST:event_label_listasTareasMouseEntered

    private void label_listasTareasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_listasTareasMouseExited
        panel_listasTareas.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_listasTareasMouseExited

    private void label_listasTareas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_listasTareas1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_listasTareas1MouseEntered

    private void label_listasTareas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_listasTareas1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_label_listasTareas1MouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_jTextField1MouseEntered

    private void jTextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_jTextField1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_jLabel1MouseExited

    private void label_myDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_myDayMouseClicked

        panel_myDay.setBackground(new Color(195, 0, 195));
        panel_tareasAsignadas.setBackground(new Color(153, 0, 153));
        panel_asignarTarea.setBackground(new Color(153, 0, 153));
        panel_crearLista.setBackground(new Color(153, 0, 153));
        panel_important.setBackground(new Color(153, 0, 153));
        panel_listasTareas.setBackground(new Color(153, 0, 153));
        panel_tareasRealizadas.setBackground(new Color(153, 0, 153));
        int id = cuentas.get(indexCuenta).getId();
        DefaultTableModel myDayModel
                = new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Importante", "Tarea", "Fecha Limite", "Completado"
                        }
                ) {
            Class[] types = new Class[]{
                java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean[]{
                true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        table_myDay.setModel(myDayModel);
        table_myDay.getTableHeader().setFont(new java.awt.Font("Litera-Serial", Font.BOLD, 15));
        table_myDay.getTableHeader().setBackground(new Color(255, 152, 204));
        table_myDay.getTableHeader().setForeground(Color.WHITE);
        table_myDay.getColumnModel().getColumn(0).setPreferredWidth(23);
        table_myDay.getColumnModel().getColumn(1).setPreferredWidth(180);
        table_myDay.getColumnModel().getColumn(2).setPreferredWidth(23);
        table_myDay.getColumnModel().getColumn(3).setPreferredWidth(23);
        table_myDay.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        panel_tareasDay.setVisible(true);
        SimpleDateFormat sd = new SimpleDateFormat("yyyy/MM/dd");
        for (Tarea tarea : tareas) {
            if (tarea.getIdCuenta() == id && !tarea.isRealizado() && !tarea.isImportante()) {
                miDia.add(tarea);
                Object[] row = new Object[4];
                row[0] = tarea.isImportante();
                row[1] = tarea.getNombreTarea();
                row[2] = sd.format(tarea.getFechaRealizar());
                row[3] = tarea.isRealizado();
                myDayModel.addRow(row);
            }
        }
        table_myDay.setModel(myDayModel);
    }//GEN-LAST:event_label_myDayMouseClicked

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
        if (jTextField1.getText().equals("Agregar Tarea")) {
            jTextField1.setText("");
            jTextField1.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_jTextField1MousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            int ver = 0;
            for (Tarea tarea : miDia) {
                if (tarea.getNombreTarea().equals(jTextField1.getText())) {
                    ver = 1;
                }
            }
            if (ver == 0) {
                Tarea t = new Tarea();
                SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
                System.out.println(d.format(dateChooser.getDate()));
                t.setFechaRealizar(dateChooser.getDate());
                t.setIdCuenta(cuentas.get(indexCuenta).getId());
                t.setIdLista(1);
                t.setImportante(false);
                t.setNombreTarea(jTextField1.getText());
                t.setRealizado(false);

                tareas.add(t);
                System.out.println(t);
                AgregarTareas();
                traerTareas();
                jTextField1.setText("Agregar Tarea");
            } else {
                JOptionPane.showMessageDialog(this, "La tarea ya existe, intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar tarea", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void label_importanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_importanteMouseClicked

        panel_myDay.setBackground(new Color(153, 0, 153));
        panel_tareasAsignadas.setBackground(new Color(153, 0, 153));
        panel_asignarTarea.setBackground(new Color(153, 0, 153));
        panel_crearLista.setBackground(new Color(153, 0, 153));
        panel_listasTareas.setBackground(new Color(153, 0, 153));
        panel_tareasRealizadas.setBackground(new Color(153, 0, 153));
        int id = cuentas.get(indexCuenta).getId();
        DefaultTableModel important = (DefaultTableModel) table_importante.getModel();
        SimpleDateFormat sd = new SimpleDateFormat("yyyy/MM/dd");
        important.setNumRows(0);
        for (Tarea tarea : tareas) {
            if (tarea.getIdCuenta() == id && !tarea.isRealizado() && tarea.isImportante()) {
                importantes.add(tarea);
                Object[] row = new Object[3];
                row[0] = tarea.getNombreTarea();
                row[1] = sd.format(tarea.getFechaRealizar());
                row[2] = tarea.isRealizado();
                important.addRow(row);
            }
        }
        table_importante.setModel(important);
        panel_importante.setVisible(true);
        panel_tareasDay.setVisible(false);
        panel_important.setBackground(new Color(194, 0, 195));
    }//GEN-LAST:event_label_importanteMouseClicked

    private void label_tareasAsignadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tareasAsignadasMouseClicked
        panel_tareasAsignadas.setBackground(new Color(195, 0, 195));
        panel_myDay.setBackground(new Color(153, 0, 153));
        panel_asignarTarea.setBackground(new Color(153, 0, 153));
        panel_crearLista.setBackground(new Color(153, 0, 153));
        panel_important.setBackground(new Color(153, 0, 153));
        panel_listasTareas.setBackground(new Color(153, 0, 153));
        panel_tareasRealizadas.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_tareasAsignadasMouseClicked

    private void label_tareasRealizadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tareasRealizadasMouseClicked
        panel_tareasRealizadas.setBackground(new Color(195, 0, 195));
        panel_myDay.setBackground(new Color(153, 0, 153));
        panel_tareasAsignadas.setBackground(new Color(153, 0, 153));
        panel_asignarTarea.setBackground(new Color(153, 0, 153));
        panel_crearLista.setBackground(new Color(153, 0, 153));
        panel_important.setBackground(new Color(153, 0, 153));
        panel_listasTareas.setBackground(new Color(153, 0, 153));
        int id = cuentas.get(indexCuenta).getId();
        SimpleDateFormat sd = new SimpleDateFormat("yyyy/MM/dd");
        panel_completados.setVisible(true);
        panel_importante.setVisible(false);
        panel_tareasDay.setVisible(false);
        DefaultTableModel completado = (DefaultTableModel) table_completados.getModel();
        completado.setNumRows(0);
        for (Tarea tarea : tareas) {
            if (tarea.getIdCuenta() == id && tarea.isRealizado()) {
                completados.add(tarea);
                Object[] row = new Object[3];
                row[0] = tarea.getNombreTarea();
                row[1] = sd.format(tarea.getFechaRealizar());
                completado.addRow(row);
            }
        }
        table_completados.setModel(completado);
    }//GEN-LAST:event_label_tareasRealizadasMouseClicked

    private void label_listasTareas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_listasTareas1MouseClicked
        panel_asignarTarea.setBackground(new Color(195, 0, 195));
        panel_myDay.setBackground(new Color(153, 0, 153));
        panel_tareasAsignadas.setBackground(new Color(153, 0, 153));
        panel_crearLista.setBackground(new Color(153, 0, 153));
        panel_important.setBackground(new Color(153, 0, 153));
        panel_listasTareas.setBackground(new Color(153, 0, 153));
        panel_tareasRealizadas.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_listasTareas1MouseClicked

    private void label_listasTareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_listasTareasMouseClicked
        panel_listasTareas.setBackground(new Color(195, 0, 195));
        panel_myDay.setBackground(new Color(153, 0, 153));
        panel_tareasAsignadas.setBackground(new Color(153, 0, 153));
        panel_asignarTarea.setBackground(new Color(153, 0, 153));
        panel_crearLista.setBackground(new Color(153, 0, 153));
        panel_important.setBackground(new Color(153, 0, 153));

        panel_tareasRealizadas.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_listasTareasMouseClicked

    private void table_myDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_myDayMouseClicked
        int i = table_myDay.getSelectedRow();
        String nombre = table_myDay.getValueAt(i, 1).toString();
        DefaultTableModel m = (DefaultTableModel) table_myDay.getModel();
        if ((Boolean) table_myDay.getValueAt(table_myDay.getSelectedRow(), 0) == true) {
            m.removeRow(table_myDay.getSelectedRow());
            for (Tarea tarea : tareas) {
                if (tarea.getNombreTarea().equals(nombre)) {
                    tarea.setImportante(true);
                    ponerTareaImportante(tarea.getIdTarea());
                }
            }
            for (Tarea tarea : miDia) {
                if (tarea.getNombreTarea().equals(nombre)) {
                    tarea.setImportante(true);
                }
            }
        } else if ((Boolean) table_myDay.getValueAt(table_myDay.getSelectedRow(), 3) == true) {
            m.removeRow(table_myDay.getSelectedRow());
            for (Tarea tarea : tareas) {
                if (tarea.getNombreTarea().equals(nombre)) {
                    tarea.setRealizado(true);
                    ponerTareaCompletado(tarea.getIdTarea());
                }
            }
            for (Tarea tarea : miDia) {
                if (tarea.getNombreTarea().equals(nombre)) {
                    tarea.setRealizado(true);
                }
            }
        }
    }//GEN-LAST:event_table_myDayMouseClicked

    private void table_importanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_importanteMouseClicked
        int i = table_importante.getSelectedRow();
        String nombre = table_importante.getValueAt(i, 0).toString();
        DefaultTableModel m = (DefaultTableModel) table_importante.getModel();
        if ((Boolean) table_importante.getValueAt(table_importante.getSelectedRow(), 2) == true) {
            m.removeRow(table_importante.getSelectedRow());
            for (Tarea tarea : tareas) {
                if (tarea.getNombreTarea().equals(nombre)) {
                    tarea.setRealizado(true);
                    ponerTareaCompletado(tarea.getIdTarea());
                    System.out.println("yes");
                }
            }
            for (Tarea tarea : importantes) {
                if (tarea.getNombreTarea().equals(nombre)) {
                    tarea.setRealizado(true);
                    tarea.setImportante(false);
                }
            }
        }
    }//GEN-LAST:event_table_importanteMouseClicked

    public void traerCuenta() {
        Dba db = new Dba("./DataBase.accdb");
        db.conectar();
        cuentas = new ArrayList();
        try {
            db.query.execute("select * from Cuentas");
            ResultSet rs = db.query.getResultSet();
            cuentas = new ArrayList();
            while (rs.next()) {
                Cuenta u = new Cuenta();
                u.setUser(rs.getString("usuario"));
                u.setContra(rs.getString("contra"));
                u.setId(rs.getInt("id"));
                cuentas.add(u);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
    }

    public void traerTareas() {
        Dba db = new Dba("./DataBase.accdb");
        db.conectar();
        tareas = new ArrayList();
        try {
            db.query.execute("select * from Tareas");
            ResultSet rs = db.query.getResultSet();
            tareas = new ArrayList();
            while (rs.next()) {
                Tarea t = new Tarea();
                t.setIdTarea(rs.getInt("idTarea"));
                t.setIdCuenta(rs.getInt("idCuenta"));
                t.setIdLista(rs.getInt("idLista"));
                t.setNombreTarea(rs.getString("nombre_Tarea"));
                t.setFechaRealizar(rs.getDate("fechaRealizar_tarea"));
                t.setRealizado(rs.getInt("realizado_tarea") == 1);
                t.setImportante(rs.getInt("importante_tarea") == 1);
                t.setNota(rs.getString("nota"));
                tareas.add(t);
                System.out.println(t);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();

    }

    public void AgregarTareas() {
        Dba db = new Dba("./DataBase.accdb");
        db.conectar();
        try {
            int index = 0;
            int cent = 0;
            while (cent == 0) {
                cent = 1;
                index++;
                for (Tarea tarea : tareas) {
                    if (index == tarea.getIdTarea()) {
                        cent = 0;
                    }
                }
            }
            SimpleDateFormat sd = new SimpleDateFormat("yyyy/MM/dd");
            Date d = dateChooser.getDate();
            db.query.execute("INSERT INTO tareas"
                    + " (idTarea,idCuenta,idLista,nombre_Tarea,fechaRealizar_tarea,realizado_tarea,importante_tarea,nota)"
                    + " VALUES (" + index + ",  "
                    + cuentas.get(indexCuenta).getId() + ", "
                    + 1 + ", '" + jTextField1.getText() + "', DateValue('"
                    + sd.format(d) + "'), "
                    + 0 + ", "
                    + 0 + ", '')");
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        int id = cuentas.get(indexCuenta).getId();
        DefaultTableModel myDayModel = (DefaultTableModel) table_myDay.getModel();
        myDayModel.setNumRows(0);
        SimpleDateFormat sd = new SimpleDateFormat("yyyy/MM/dd");
        for (Tarea tarea : tareas) {
            if (tarea.getIdCuenta() == id && !tarea.isRealizado() && !tarea.isImportante()) {
                Object[] row = new Object[4];
                row[0] = tarea.isImportante();
                row[1] = tarea.getNombreTarea();
                row[2] = sd.format(tarea.getFechaRealizar());
                row[3] = tarea.isRealizado();
                myDayModel.addRow(row);
            }

        }
        table_myDay.setModel(myDayModel);
    }

    public void ponerTareaImportante(int id) {
        Dba db = new Dba("./DataBase.accdb");
        db.conectar();
        try {
            db.query.execute("update Tareas set importante_tarea= " + 1 + " where idTarea= " + id);
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();

    }

    public void ponerTareaCompletado(int id) {
        Dba db = new Dba("./DataBase.accdb");
        db.conectar();
        try {
            db.query.execute("update Tareas set realizado_tarea= " + 1 + " where idTarea= " + id);
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myToDo(indexCuenta).setVisible(true);
            }
        });
    }
    private int xMouse;
    private int yMouse;
    private static int indexCuenta;
    //private SimpleDateFormat sd = new SimpleDateFormat("yyyy/MM/dd");
    private ArrayList<Cuenta> cuentas = new ArrayList();
    private ArrayList<Tarea> tareas = new ArrayList();
    private ArrayList<Tarea> miDia = new ArrayList();
    private ArrayList<Tarea> importantes = new ArrayList();
    private ArrayList<Tarea> completados = new ArrayList();
    private ArrayList<ListaTarea> listaTareas = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_myToDo;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JPanel header_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_exit_myToDo;
    private javax.swing.JLabel label_importante;
    private javax.swing.JLabel label_listasTareas;
    private javax.swing.JLabel label_listasTareas1;
    private javax.swing.JLabel label_minimize_myToDo;
    private javax.swing.JLabel label_myDay;
    private javax.swing.JLabel label_tareasAsignadas;
    private javax.swing.JLabel label_tareasRealizadas;
    private javax.swing.JLabel myDay_Title;
    private javax.swing.JPanel panel_asignarTarea;
    private javax.swing.JPanel panel_completados;
    private javax.swing.JPanel panel_crearLista;
    private javax.swing.JPanel panel_eventos;
    private javax.swing.JPanel panel_exit_myToDo;
    private javax.swing.JPanel panel_important;
    private javax.swing.JPanel panel_importante;
    private javax.swing.JPanel panel_listasTareas;
    private javax.swing.JPanel panel_minimize_myToDo;
    private javax.swing.JPanel panel_myDay;
    private javax.swing.JPanel panel_tareasAsignadas;
    private javax.swing.JPanel panel_tareasDay;
    private javax.swing.JPanel panel_tareasRealizadas;
    private javax.swing.JTable table_completados;
    private javax.swing.JTable table_importante;
    private javax.swing.JTable table_listaTareas;
    private javax.swing.JTable table_myDay;
    // End of variables declaration//GEN-END:variables
}
