package ToDo;

import Conexiones.Dba;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import loginFrames.Administrador;
import loginFrames.Cuenta;
import loginFrames.DefaultLoginFrame;
import loginFrames.MenuPrincipal;

/**
 *
 * @author Usuario
 */
public class myToDo extends javax.swing.JFrame {

    /**
     * Creates new form myToDo
     *
     * @param indexCuenta
     * @param cuentas
     */
    public myToDo(int indexCuenta) {
        initComponents();
        traerCuenta();
        myToDo.indexCuenta = indexCuenta;
        jTable1.getTableHeader().setFont(new java.awt.Font("Litera-Serial", 0, 14));
        jTable1.getTableHeader().setBackground(new Color(255, 152, 204));
        jTable1.getTableHeader().setForeground(Color.WHITE);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
//        a();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_myToDo = new javax.swing.JPanel();
        header_menu = new javax.swing.JPanel();
        panel_minimize_myToDo = new javax.swing.JPanel();
        label_minimize_myToDo = new javax.swing.JLabel();
        panel_exit_myToDo = new javax.swing.JPanel();
        label_exit_myToDo = new javax.swing.JLabel();
        panel_eventos = new javax.swing.JPanel();
        panel_myDay = new javax.swing.JPanel();
        label_myDay = new javax.swing.JLabel();
        panel_important = new javax.swing.JPanel();
        label_importante = new javax.swing.JLabel();
        panel_tareasAsignadas = new javax.swing.JPanel();
        label_tareasAsignadas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panel_tareasRealizadas = new javax.swing.JPanel();
        label_tareasRealizadas = new javax.swing.JLabel();
        panel_listasTareas = new javax.swing.JPanel();
        label_listasTareas = new javax.swing.JLabel();
        myDay_Title = new javax.swing.JLabel();
        panel_crearLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel_listasTareas1 = new javax.swing.JPanel();
        label_listasTareas1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg_myToDo.setBackground(new java.awt.Color(252, 255, 219));
        bg_myToDo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header_menu.setBackground(new java.awt.Color(122, 68, 149));
        header_menu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header_menuMouseDragged(evt);
            }
        });
        header_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_menuMousePressed(evt);
            }
        });

        panel_minimize_myToDo.setBackground(new java.awt.Color(122, 68, 149));

        label_minimize_myToDo.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        label_minimize_myToDo.setForeground(new java.awt.Color(255, 255, 255));
        label_minimize_myToDo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_minimize_myToDo.setText("🗕");
        label_minimize_myToDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_minimize_myToDoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_minimize_myToDoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_minimize_myToDoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_minimize_myToDoLayout = new javax.swing.GroupLayout(panel_minimize_myToDo);
        panel_minimize_myToDo.setLayout(panel_minimize_myToDoLayout);
        panel_minimize_myToDoLayout.setHorizontalGroup(
            panel_minimize_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_minimize_myToDoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_minimize_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_minimize_myToDoLayout.setVerticalGroup(
            panel_minimize_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_minimize_myToDoLayout.createSequentialGroup()
                .addComponent(label_minimize_myToDo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_exit_myToDo.setBackground(new java.awt.Color(122, 68, 149));

        label_exit_myToDo.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        label_exit_myToDo.setForeground(new java.awt.Color(255, 255, 255));
        label_exit_myToDo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit_myToDo.setText("🗙");
        label_exit_myToDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exit_myToDoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exit_myToDoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exit_myToDoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_exit_myToDoLayout = new javax.swing.GroupLayout(panel_exit_myToDo);
        panel_exit_myToDo.setLayout(panel_exit_myToDoLayout);
        panel_exit_myToDoLayout.setHorizontalGroup(
            panel_exit_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exit_myToDoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_exit_myToDoLayout.setVerticalGroup(
            panel_exit_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exit_myToDoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout header_menuLayout = new javax.swing.GroupLayout(header_menu);
        header_menu.setLayout(header_menuLayout);
        header_menuLayout.setHorizontalGroup(
            header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_menuLayout.createSequentialGroup()
                .addContainerGap(934, Short.MAX_VALUE)
                .addComponent(panel_minimize_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_menuLayout.setVerticalGroup(
            header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_menuLayout.createSequentialGroup()
                .addGroup(header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_minimize_myToDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(header_menuLayout.createSequentialGroup()
                        .addComponent(panel_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bg_myToDo.add(header_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        panel_eventos.setBackground(new java.awt.Color(172, 112, 168));

        panel_myDay.setBackground(new java.awt.Color(153, 0, 153));

        label_myDay.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_myDay.setForeground(new java.awt.Color(255, 255, 255));
        label_myDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_myDay.setText("My Day");
        label_myDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_myDayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_myDayMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_myDayLayout = new javax.swing.GroupLayout(panel_myDay);
        panel_myDay.setLayout(panel_myDayLayout);
        panel_myDayLayout.setHorizontalGroup(
            panel_myDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_myDayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_myDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_myDayLayout.setVerticalGroup(
            panel_myDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_myDay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_important.setBackground(new java.awt.Color(153, 0, 153));

        label_importante.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_importante.setForeground(new java.awt.Color(255, 255, 255));
        label_importante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_importante.setText("Importante");
        label_importante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_importanteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_importanteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_importantLayout = new javax.swing.GroupLayout(panel_important);
        panel_important.setLayout(panel_importantLayout);
        panel_importantLayout.setHorizontalGroup(
            panel_importantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_importantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_importante, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_importantLayout.setVerticalGroup(
            panel_importantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_importante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_tareasAsignadas.setBackground(new java.awt.Color(153, 0, 153));

        label_tareasAsignadas.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_tareasAsignadas.setForeground(new java.awt.Color(255, 255, 255));
        label_tareasAsignadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tareasAsignadas.setText("Tareas Asignadas");
        label_tareasAsignadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_tareasAsignadasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_tareasAsignadasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_tareasAsignadasLayout = new javax.swing.GroupLayout(panel_tareasAsignadas);
        panel_tareasAsignadas.setLayout(panel_tareasAsignadasLayout);
        panel_tareasAsignadasLayout.setHorizontalGroup(
            panel_tareasAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tareasAsignadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_tareasAsignadas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tareasAsignadasLayout.setVerticalGroup(
            panel_tareasAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_tareasAsignadas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(102, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 0, 102));

        panel_tareasRealizadas.setBackground(new java.awt.Color(153, 0, 153));

        label_tareasRealizadas.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_tareasRealizadas.setForeground(new java.awt.Color(255, 255, 255));
        label_tareasRealizadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tareasRealizadas.setText("Tareas Realizadas");
        label_tareasRealizadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_tareasRealizadasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_tareasRealizadasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_tareasRealizadasLayout = new javax.swing.GroupLayout(panel_tareasRealizadas);
        panel_tareasRealizadas.setLayout(panel_tareasRealizadasLayout);
        panel_tareasRealizadasLayout.setHorizontalGroup(
            panel_tareasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tareasRealizadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_tareasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tareasRealizadasLayout.setVerticalGroup(
            panel_tareasRealizadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_tareasRealizadas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_listasTareas.setBackground(new java.awt.Color(153, 0, 153));

        label_listasTareas.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_listasTareas.setForeground(new java.awt.Color(255, 255, 255));
        label_listasTareas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_listasTareas.setText("+ Lista de Tareas");
        label_listasTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_listasTareasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_listasTareasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_listasTareasLayout = new javax.swing.GroupLayout(panel_listasTareas);
        panel_listasTareas.setLayout(panel_listasTareasLayout);
        panel_listasTareasLayout.setHorizontalGroup(
            panel_listasTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_listasTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_listasTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_listasTareasLayout.setVerticalGroup(
            panel_listasTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_listasTareas, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        myDay_Title.setFont(new java.awt.Font("Litera-Serial", 0, 36)); // NOI18N
        myDay_Title.setForeground(new java.awt.Color(255, 255, 255));
        myDay_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myDay_Title.setText("myDay");

        panel_crearLista.setBackground(new java.awt.Color(153, 0, 153));

        jTable1.setBackground(new java.awt.Color(204, 51, 255));
        jTable1.setFont(new java.awt.Font("Litera-Serial", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"HOLA"},
                {"ADIOS"},
                {null}
            },
            new String [] {
                "Lista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(204, 153, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panel_crearListaLayout = new javax.swing.GroupLayout(panel_crearLista);
        panel_crearLista.setLayout(panel_crearListaLayout);
        panel_crearListaLayout.setHorizontalGroup(
            panel_crearListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crearListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_crearListaLayout.setVerticalGroup(
            panel_crearListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_crearListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        panel_listasTareas1.setBackground(new java.awt.Color(153, 0, 153));

        label_listasTareas1.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        label_listasTareas1.setForeground(new java.awt.Color(255, 255, 255));
        label_listasTareas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_listasTareas1.setText("+ Asignar Tarea");
        label_listasTareas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_listasTareas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_listasTareas1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_listasTareas1Layout = new javax.swing.GroupLayout(panel_listasTareas1);
        panel_listasTareas1.setLayout(panel_listasTareas1Layout);
        panel_listasTareas1Layout.setHorizontalGroup(
            panel_listasTareas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_listasTareas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_listasTareas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_listasTareas1Layout.setVerticalGroup(
            panel_listasTareas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_listasTareas1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_eventosLayout = new javax.swing.GroupLayout(panel_eventos);
        panel_eventos.setLayout(panel_eventosLayout);
        panel_eventosLayout.setHorizontalGroup(
            panel_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_myDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_important, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_tareasAsignadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_tareasRealizadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_listasTareas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_eventosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(myDay_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_crearLista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_listasTareas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_eventosLayout.setVerticalGroup(
            panel_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_eventosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(myDay_Title)
                .addGap(18, 18, 18)
                .addComponent(panel_myDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_important, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tareasAsignadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tareasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_listasTareas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_listasTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_crearLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg_myToDo.add(panel_eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 520));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg_myToDo.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 570, 440));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        bg_myToDo.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 570, 440));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        bg_myToDo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 570, 440));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        bg_myToDo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 570, 440));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        bg_myToDo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 570, 440));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        bg_myToDo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 190, 270));
        bg_myToDo.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_myToDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_myToDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_minimize_myToDoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_myToDoMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_label_minimize_myToDoMouseClicked

    private void label_minimize_myToDoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_myToDoMouseEntered
        panel_minimize_myToDo.setBackground(new Color(122, 96, 149));
    }//GEN-LAST:event_label_minimize_myToDoMouseEntered

    private void label_minimize_myToDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_myToDoMouseExited
        panel_minimize_myToDo.setBackground(header_menu.getBackground());
    }//GEN-LAST:event_label_minimize_myToDoMouseExited

    private void label_exit_myToDoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myToDoMouseClicked
        int yesno = JOptionPane.showConfirmDialog(this, "Salir y guardar cambios?", "Salir", 0);
        if (yesno == 0) {
            if ("Kevin".equals(cuentas.get(indexCuenta).getUser())) {
                setVisible(false);
                new Administrador(indexCuenta).setVisible(true);
            } else {
                setVisible(false);
                new MenuPrincipal(indexCuenta).setVisible(true);
            }
        }
    }//GEN-LAST:event_label_exit_myToDoMouseClicked

    private void label_exit_myToDoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myToDoMouseEntered
        panel_exit_myToDo.setBackground(Color.red);
    }//GEN-LAST:event_label_exit_myToDoMouseEntered

    private void label_exit_myToDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myToDoMouseExited
        panel_exit_myToDo.setBackground(header_menu.getBackground());
    }//GEN-LAST:event_label_exit_myToDoMouseExited

    private void header_menuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_menuMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header_menuMouseDragged

    private void header_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_menuMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header_menuMousePressed

    private void label_myDayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_myDayMouseEntered
        panel_myDay.setBackground(new Color(195, 0, 195));
    }//GEN-LAST:event_label_myDayMouseEntered

    private void label_myDayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_myDayMouseExited
        panel_myDay.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_myDayMouseExited

    private void label_importanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_importanteMouseEntered
        panel_important.setBackground(new Color(195, 0, 195));
    }//GEN-LAST:event_label_importanteMouseEntered

    private void label_importanteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_importanteMouseExited
        panel_important.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_importanteMouseExited

    private void label_tareasAsignadasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tareasAsignadasMouseEntered
        panel_tareasAsignadas.setBackground(new Color(195, 0, 195));
    }//GEN-LAST:event_label_tareasAsignadasMouseEntered

    private void label_tareasAsignadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tareasAsignadasMouseExited
        panel_tareasAsignadas.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_tareasAsignadasMouseExited

    private void label_tareasRealizadasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tareasRealizadasMouseEntered
        panel_tareasRealizadas.setBackground(new Color(195, 0, 195));
    }//GEN-LAST:event_label_tareasRealizadasMouseEntered

    private void label_tareasRealizadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_tareasRealizadasMouseExited
        panel_tareasRealizadas.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_tareasRealizadasMouseExited

    private void label_listasTareasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_listasTareasMouseEntered
        panel_listasTareas.setBackground(new Color(195, 0, 195));
    }//GEN-LAST:event_label_listasTareasMouseEntered

    private void label_listasTareasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_listasTareasMouseExited
        panel_listasTareas.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_label_listasTareasMouseExited

    private void label_listasTareas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_listasTareas1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_listasTareas1MouseEntered

    private void label_listasTareas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_listasTareas1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_label_listasTareas1MouseExited
//    public void a() {
//        JFrame frame = new JFrame();
//        JPanel panel = new JPanel(new GridLayout());
//        JScrollPane scroll = new JScrollPane();
//
//        frame.setSize(800, 500);
//        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        frame.setLocationByPlatform(true);
//
//        panel = new JPanel(new GridLayout(0, 1, 10, 10));
//        for (int i = 0; i < 15; i++) {
//            JButton button = new JButton("Adios");
//            JButton button2 = new JButton("Hola");
//            JPanel panel1 = new JPanel();
//            panel1.setSize(100, 100);
//            panel1.setBackground(Color.red);
//            JLabel label = new JLabel("HOLA");
//            button.addActionListener(e -> selectionButtonPressed(label));
//            button2.addActionListener(e -> selectionButtonPressed1(label));
//            panel1.add(button);
//            panel1.add(label);
//            panel1.add(button2);
//            jPanel2.add(panel1);
//        }
//
//        pack();
//        setVisible(true);
//        //panel.setVisible(true);
//        add(jPanel2, BorderLayout.NORTH);
//        add(new JScrollPane(jPanel2), BorderLayout.CENTER);
//    }
//
//    public void selectionButtonPressed(JLabel l) {
//        l.setText("Adios");
//    }
//
//    public void selectionButtonPressed1(JLabel l) {
//        l.setText("Hola");
//    }

    public void traerCuenta() {
        Dba db = new Dba("./DataBaseProyectoFinal.accdb");
        db.conectar();
        cuentas = new ArrayList();
        try {
            db.query.execute("select * from Cuentas");
            ResultSet rs = db.query.getResultSet();
            cuentas = new ArrayList();
            while (rs.next()) {
                Cuenta u = new Cuenta();
                u.setUser(rs.getString("usuario"));
                u.setContra(rs.getString("contra"));
                cuentas.add(u);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myToDo(indexCuenta).setVisible(true);
            }
        });
    }
    private int xMouse;
    private int yMouse;
    private static int indexCuenta;
    private ArrayList<Cuenta> cuentas = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_myToDo;
    private javax.swing.JPanel header_menu;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel label_exit_myToDo;
    private javax.swing.JLabel label_importante;
    private javax.swing.JLabel label_listasTareas;
    private javax.swing.JLabel label_listasTareas1;
    private javax.swing.JLabel label_minimize_myToDo;
    private javax.swing.JLabel label_myDay;
    private javax.swing.JLabel label_tareasAsignadas;
    private javax.swing.JLabel label_tareasRealizadas;
    private javax.swing.JLabel myDay_Title;
    private javax.swing.JPanel panel_crearLista;
    private javax.swing.JPanel panel_eventos;
    private javax.swing.JPanel panel_exit_myToDo;
    private javax.swing.JPanel panel_important;
    private javax.swing.JPanel panel_listasTareas;
    private javax.swing.JPanel panel_listasTareas1;
    private javax.swing.JPanel panel_minimize_myToDo;
    private javax.swing.JPanel panel_myDay;
    private javax.swing.JPanel panel_tareasAsignadas;
    private javax.swing.JPanel panel_tareasRealizadas;
    // End of variables declaration//GEN-END:variables
}
