package ToDo;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import loginFrames.Cuenta;
import loginFrames.DefaultLoginFrame;
import loginFrames.MenuPrincipal;

/**
 *
 * @author Usuario
 */
public class myToDo extends javax.swing.JFrame {

    /**
     * Creates new form myToDo
     * @param indexCuenta
     * @param cuentas
     */
    public myToDo(int indexCuenta, ArrayList<Cuenta> cuentas) {
        initComponents();
        myToDo.cuentas = cuentas;
        myToDo.indexCuenta=indexCuenta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_myToDo = new javax.swing.JPanel();
        header_menu = new javax.swing.JPanel();
        panel_minimize_myToDo = new javax.swing.JPanel();
        label_minimize_myToDo = new javax.swing.JLabel();
        panel_exit_myToDo = new javax.swing.JPanel();
        label_exit_myToDo = new javax.swing.JLabel();
        menuBar_menu = new javax.swing.JPanel();
        panel_salir_myToDo = new javax.swing.JPanel();
        salir_myToDo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg_myToDo.setBackground(new java.awt.Color(252, 226, 219));
        bg_myToDo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header_menu.setBackground(new java.awt.Color(122, 68, 149));
        header_menu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header_menuMouseDragged(evt);
            }
        });
        header_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_menuMousePressed(evt);
            }
        });

        panel_minimize_myToDo.setBackground(new java.awt.Color(122, 68, 149));

        label_minimize_myToDo.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        label_minimize_myToDo.setForeground(new java.awt.Color(255, 255, 255));
        label_minimize_myToDo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_minimize_myToDo.setText("🗕");
        label_minimize_myToDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_minimize_myToDoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_minimize_myToDoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_minimize_myToDoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_minimize_myToDoLayout = new javax.swing.GroupLayout(panel_minimize_myToDo);
        panel_minimize_myToDo.setLayout(panel_minimize_myToDoLayout);
        panel_minimize_myToDoLayout.setHorizontalGroup(
            panel_minimize_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_minimize_myToDoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_minimize_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_minimize_myToDoLayout.setVerticalGroup(
            panel_minimize_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_minimize_myToDoLayout.createSequentialGroup()
                .addComponent(label_minimize_myToDo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_exit_myToDo.setBackground(new java.awt.Color(122, 68, 149));

        label_exit_myToDo.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        label_exit_myToDo.setForeground(new java.awt.Color(255, 255, 255));
        label_exit_myToDo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit_myToDo.setText("🗙");
        label_exit_myToDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exit_myToDoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exit_myToDoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exit_myToDoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_exit_myToDoLayout = new javax.swing.GroupLayout(panel_exit_myToDo);
        panel_exit_myToDo.setLayout(panel_exit_myToDoLayout);
        panel_exit_myToDoLayout.setHorizontalGroup(
            panel_exit_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exit_myToDoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_exit_myToDoLayout.setVerticalGroup(
            panel_exit_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exit_myToDoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout header_menuLayout = new javax.swing.GroupLayout(header_menu);
        header_menu.setLayout(header_menuLayout);
        header_menuLayout.setHorizontalGroup(
            header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_menuLayout.createSequentialGroup()
                .addContainerGap(684, Short.MAX_VALUE)
                .addComponent(panel_minimize_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_menuLayout.setVerticalGroup(
            header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_menuLayout.createSequentialGroup()
                .addGroup(header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_minimize_myToDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(header_menuLayout.createSequentialGroup()
                        .addComponent(panel_exit_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bg_myToDo.add(header_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 30));

        menuBar_menu.setBackground(new java.awt.Color(153, 153, 153));

        panel_salir_myToDo.setBackground(new java.awt.Color(153, 153, 153));
        panel_salir_myToDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_salir_myToDoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_salir_myToDoMouseExited(evt);
            }
        });

        salir_myToDo.setForeground(new java.awt.Color(255, 255, 255));
        salir_myToDo.setText("Salir");

        javax.swing.GroupLayout panel_salir_myToDoLayout = new javax.swing.GroupLayout(panel_salir_myToDo);
        panel_salir_myToDo.setLayout(panel_salir_myToDoLayout);
        panel_salir_myToDoLayout.setHorizontalGroup(
            panel_salir_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_salir_myToDoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salir_myToDo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_salir_myToDoLayout.setVerticalGroup(
            panel_salir_myToDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salir_myToDo, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menuBar_menuLayout = new javax.swing.GroupLayout(menuBar_menu);
        menuBar_menu.setLayout(menuBar_menuLayout);
        menuBar_menuLayout.setHorizontalGroup(
            menuBar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBar_menuLayout.createSequentialGroup()
                .addComponent(panel_salir_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 705, Short.MAX_VALUE))
        );
        menuBar_menuLayout.setVerticalGroup(
            menuBar_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBar_menuLayout.createSequentialGroup()
                .addComponent(panel_salir_myToDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg_myToDo.add(menuBar_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 750, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_myToDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_myToDo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_minimize_myToDoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_myToDoMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_label_minimize_myToDoMouseClicked

    private void label_minimize_myToDoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_myToDoMouseEntered
        panel_minimize_myToDo.setBackground(new Color(122, 96, 149));
    }//GEN-LAST:event_label_minimize_myToDoMouseEntered

    private void label_minimize_myToDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimize_myToDoMouseExited
        panel_minimize_myToDo.setBackground(header_menu.getBackground());
    }//GEN-LAST:event_label_minimize_myToDoMouseExited

    private void label_exit_myToDoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myToDoMouseClicked
        int yesno = JOptionPane.showConfirmDialog(this, "Salir y guardar cambios?", "Salir", 0);
        if (yesno == 0) {
            setVisible(false);
            new MenuPrincipal(indexCuenta, cuentas).setVisible(true);
        } else {

        }
    }//GEN-LAST:event_label_exit_myToDoMouseClicked

    private void label_exit_myToDoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myToDoMouseEntered
        panel_exit_myToDo.setBackground(Color.red);
    }//GEN-LAST:event_label_exit_myToDoMouseEntered

    private void label_exit_myToDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myToDoMouseExited
        panel_exit_myToDo.setBackground(header_menu.getBackground());
    }//GEN-LAST:event_label_exit_myToDoMouseExited

    private void header_menuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_menuMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header_menuMouseDragged

    private void header_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_menuMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header_menuMousePressed

    private void panel_salir_myToDoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_salir_myToDoMouseEntered
        panel_salir_myToDo.setBackground(Color.LIGHT_GRAY);
        salir_myToDo.setForeground(Color.BLACK);
    }//GEN-LAST:event_panel_salir_myToDoMouseEntered

    private void panel_salir_myToDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_salir_myToDoMouseExited
        panel_salir_myToDo.setBackground(new Color(153,153,153));
        salir_myToDo.setForeground(Color.WHITE);
    }//GEN-LAST:event_panel_salir_myToDoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myToDo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myToDo(indexCuenta, cuentas).setVisible(true);
            }
        });
    }
    private int xMouse;
    private int yMouse;
    private static int indexCuenta;
    private static ArrayList<Cuenta> cuentas;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_myToDo;
    private javax.swing.JPanel header_menu;
    private javax.swing.JLabel label_exit_myToDo;
    private javax.swing.JLabel label_minimize_myToDo;
    private javax.swing.JPanel menuBar_menu;
    private javax.swing.JPanel panel_exit_myToDo;
    private javax.swing.JPanel panel_minimize_myToDo;
    private javax.swing.JPanel panel_salir_myToDo;
    private javax.swing.JLabel salir_myToDo;
    // End of variables declaration//GEN-END:variables
}
