package Correo;

import Conexiones.Dba;
import Correo.ConeccionCorreo;
import Correo.CorreoUsuarios;
import Correo.Servidor;
import java.awt.Color;
import java.security.MessageDigest;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import loginFrames.Administrador;
import loginFrames.Cuenta;
import loginFrames.MenuPrincipal;

/**
 *
 * @author Usuario
 */
public class Ingresar extends javax.swing.JFrame {

    /**
     * Creates new form Ingresar
     */
    public Ingresar(int indexCuenta) {
        traerCuenta();
        traerCorreoUsuarios();
        initComponents();
        pack();
        setLocationRelativeTo(null);
        this.indexCuenta = indexCuenta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        usuario = new javax.swing.JTextField();
        icon_usuario_iniciar = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        icon_contra_iniciar = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        icon_visualize_iniciar = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        header_menu2 = new javax.swing.JPanel();
        panel_exit_myMail2 = new javax.swing.JPanel();
        label_exit_myMail2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));

        jPanel9.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresar a Cuenta");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(172, 112, 168));

        usuario.setBackground(new java.awt.Color(172, 112, 168));
        usuario.setFont(new java.awt.Font("Litera-Serial", 0, 12)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario");
        usuario.setBorder(null);
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioMousePressed(evt);
            }
        });

        icon_usuario_iniciar.setBackground(new java.awt.Color(255, 0, 51));
        icon_usuario_iniciar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        icon_usuario_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        icon_usuario_iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_usuario_iniciar.setText("👤 ");
        icon_usuario_iniciar.setMaximumSize(new java.awt.Dimension(22, 19));
        icon_usuario_iniciar.setMinimumSize(new java.awt.Dimension(22, 19));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon_usuario_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(icon_usuario_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(172, 112, 168));

        icon_contra_iniciar.setBackground(new java.awt.Color(255, 0, 51));
        icon_contra_iniciar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        icon_contra_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        icon_contra_iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_contra_iniciar.setText("🔒");

        password.setBackground(new java.awt.Color(172, 112, 168));
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Contraseña");
        password.setBorder(null);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordMousePressed(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        icon_visualize_iniciar.setBackground(new java.awt.Color(255, 0, 51));
        icon_visualize_iniciar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        icon_visualize_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        icon_visualize_iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_visualize_iniciar.setText("👁");
        icon_visualize_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_visualize_iniciarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon_contra_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_visualize_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addComponent(icon_contra_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(icon_visualize_iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(153, 0, 153));

        jLabel2.setFont(new java.awt.Font("Litera-Serial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingresar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        header_menu2.setBackground(new java.awt.Color(122, 68, 149));
        header_menu2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header_menu2MouseDragged(evt);
            }
        });
        header_menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_menu2MousePressed(evt);
            }
        });

        panel_exit_myMail2.setBackground(new java.awt.Color(122, 68, 149));

        label_exit_myMail2.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        label_exit_myMail2.setForeground(new java.awt.Color(255, 255, 255));
        label_exit_myMail2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit_myMail2.setText("🗙");
        label_exit_myMail2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exit_myMail2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exit_myMail2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exit_myMail2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_exit_myMail2Layout = new javax.swing.GroupLayout(panel_exit_myMail2);
        panel_exit_myMail2.setLayout(panel_exit_myMail2Layout);
        panel_exit_myMail2Layout.setHorizontalGroup(
            panel_exit_myMail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exit_myMail2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_exit_myMail2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_exit_myMail2Layout.setVerticalGroup(
            panel_exit_myMail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exit_myMail2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_exit_myMail2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout header_menu2Layout = new javax.swing.GroupLayout(header_menu2);
        header_menu2.setLayout(header_menu2Layout);
        header_menu2Layout.setHorizontalGroup(
            header_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_menu2Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(panel_exit_myMail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_menu2Layout.setVerticalGroup(
            header_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_exit_myMail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(header_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(header_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMousePressed
        if (usuario.getText().equals("Usuario")) {
            usuario.setText("");
            usuario.setForeground(Color.WHITE);
        }

        if (String.valueOf(password.getPassword()).isEmpty()) {
            password.setEchoChar((char) 0);
            password.setText("Contraseña");
            password.setForeground(Color.WHITE);
            bruh = 0;
        }
    }//GEN-LAST:event_usuarioMousePressed

    private void passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMousePressed
        if (usuario.getText().isEmpty()) {
            usuario.setText("Usuario");
            usuario.setForeground(Color.WHITE);
        }

        if (String.valueOf(password.getPassword()).equals("Contraseña")) {
            password.setText("");
            password.setForeground(Color.WHITE);
            password.setEchoChar('*');
            bruh = 0;
        }
    }//GEN-LAST:event_passwordMousePressed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed

    }//GEN-LAST:event_passwordActionPerformed

    private void icon_visualize_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_visualize_iniciarMouseClicked
        if (bruh == 0 && !"Contraseña".equals(password.getText())) {
            password.setEchoChar((char) 0);
            bruh = 1;
        } else if (bruh == 1 && !"Contraseña".equals(password.getText())) {
            password.setEchoChar('*');
            bruh = 0;
        } else {
            bruh = 0;
        }
    }//GEN-LAST:event_icon_visualize_iniciarMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String user = usuario.getText();
        String contra = password.getText();
        boolean ver = false;
        System.out.println("outside try");
        try {
            System.out.println("start");
            Servidor server = new Servidor("smtp.office365.com", "587", user, contra);
            server.conectar();
            
            ConeccionCorreo mail=new ConeccionCorreo(server.getSession());
            server.enviarCorreo(mail);
        } catch (NullPointerException e) {
            ver = true;
        } catch(Exception e){
            e.printStackTrace();
        }
        if(ver==true){
            JOptionPane.showMessageDialog(this, "Conectado", "Exito", JOptionPane.INFORMATION_MESSAGE);
            ponerCorreo(user, contra);
            new myMail(indexCuenta).setVisible(true);
            setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Correo Invalido", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void label_exit_myMail2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myMail2MouseClicked
        int yesno = JOptionPane.showConfirmDialog(this, "Salir?", "Salir", 0);
        if (yesno == 0) {
            if ("Kevin".equals(cuentas.get(indexCuenta).getUser())) {
                new Administrador(indexCuenta).setVisible(true);
                setVisible(false);
            } else {
                new MenuPrincipal(indexCuenta).setVisible(true);
                setVisible(false);
            }
        }

    }//GEN-LAST:event_label_exit_myMail2MouseClicked

    private void label_exit_myMail2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myMail2MouseEntered
        panel_exit_myMail2.setBackground(Color.red);
    }//GEN-LAST:event_label_exit_myMail2MouseEntered

    private void label_exit_myMail2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exit_myMail2MouseExited
        panel_exit_myMail2.setBackground(header_menu2.getBackground());
    }//GEN-LAST:event_label_exit_myMail2MouseExited

    private void header_menu2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_menu2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header_menu2MouseDragged

    private void header_menu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_menu2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header_menu2MousePressed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jPanel12.setBackground(new Color(195, 0, 195));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jPanel12.setBackground(new Color(153, 0, 153));
    }//GEN-LAST:event_jLabel2MouseExited

    public static String encrypt(String password) {
        try {
            MessageDigest m = MessageDigest.getInstance("MD5");
            m.update(password.getBytes());
            byte[] bytes = m.digest();
            StringBuilder s = new StringBuilder();
            for (int i = 0; i < bytes.length; i++) {
                s.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }
            return s.toString();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "";
    }

    public void traerCuenta() {
        Dba db = new Dba("./DataBase.accdb");
        db.conectar();
        cuentas = new ArrayList();
        try {
            db.query.execute("select * from Cuentas");
            ResultSet rs = db.query.getResultSet();
            cuentas = new ArrayList();
            while (rs.next()) {
                Cuenta u = new Cuenta();
                u.setUser(rs.getString("usuario"));
                u.setContra(rs.getString("contra"));
                u.setId(rs.getInt("id"));
                cuentas.add(u);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al traer datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        db.desconectar();
    }

    public void traerCorreoUsuarios() {
        Dba db = new Dba("./DataBase.accdb");
        db.conectar();
        correosUsuarios = new ArrayList();
        try {
            db.query.execute("select * from borradores");
            ResultSet rs = db.query.getResultSet();
            correosUsuarios = new ArrayList();
            while (rs.next()) {

                CorreoUsuarios cu = new CorreoUsuarios();
                cu.setIdCorreo(rs.getInt("idCorreo"));
                cu.setIdCuenta(rs.getInt("idCuenta"));
                cu.setContra(rs.getString("contra"));
                cu.setUsuario(rs.getString("usuario"));
                correosUsuarios.add(cu);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
    }

    public void ponerCorreo(String user, String contra){
        Dba db = new Dba("./DataBase.accdb");
        db.conectar();
        try{
            db.query.execute("insert into correos (idCuenta,correo,contra) "
                    + "VALUES ("+cuentas.get(indexCuenta).getId()+", '"+user+"', '"+contra+"')");
            db.commit();
        }catch(Exception e){
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar(indexCuenta).setVisible(true);
            }
        });
    }
    private static int indexCuenta;
    private int bruh;
    private int xMouse;
    private int yMouse;
    private ArrayList<Cuenta> cuentas;
    private ArrayList<CorreoUsuarios> correosUsuarios;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header_menu2;
    private javax.swing.JLabel icon_contra_iniciar;
    private javax.swing.JLabel icon_usuario_iniciar;
    private javax.swing.JLabel icon_visualize_iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label_exit_myMail2;
    private javax.swing.JPanel panel_exit_myMail2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
